# Generated by Django 5.1.6 on 2025-03-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0003_mediaproject_drive_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaproject',
            old_name='drive_link',
            new_name='drive_web_view_link',
        ),
        migrations.AddField(
            model_name='mediaproject',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
