# Generated by Django 5.1.6 on 2025-03-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0004_rename_drive_link_mediaproject_drive_web_view_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/thumbnails/'),
        ),
    ]
